---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmpsfti-website-deployment
  namespace: hello
spec:
  selector:
    matchLabels:
      app: hmpsfti-website
  replicas: 2
  template:
    metadata:
      labels:
        app: hmpsfti-website
    spec:
      containers:
        - name: hmpsfti-website
          image: asia-southeast2-docker.pkg.dev/playground-194610/test-ci-cd/hmpsfti-website:IMAGE_VERSION
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hmpsfti-website-service
  namespace: hello
spec:
  selector:
    app: hmpsfti-website
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
